decorations: none
window_opacity: 0.9
render_timer: false
draw_bold_text_with_bright_colors: true

env:
  TERM: xterm-256color
window:
  padding:
    x: 0
    y: 0
  dynamic_padding: false
font:
  size: 7
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
  normal:
    family: JetBrains Mono
    style: Regular
  bold:
    family: JetBrains Mono
    style: ExtraBold
  italic:
    family: JetBrains Mono
    style: Italic

shell:
  program: /usr/bin/zsh
  args:
    - --login

# Grvbox Custom
colors:
  primary:
    background: "#1D2021"
    foreground: "#ebdbb2"
  normal:
    black: "#282828"
    red: "#cc241d"
    green: "#949E14"
    yellow: "#d79921"
    blue: "#2091ad"
    magenta: "#b16286"
    cyan: "#5ea860"
    white: "#a89984"
  bright:
    black: "#928374"
    red: "#fb4934"
    green: "#b8bb26"
    yellow: "#fabd2f"
    blue: "#83a598"
    magenta: "#d3869b"
    cyan: "#8ec07c"
    white: "#ebdbb2"
