font:
  size: 12
  normal:
    family: Hack Nerd Font Mono
    style: Regular
  bold:
    family: Hack Nerd Font Mono
  italic:
    family: Hack Nerd Font Mono

colors:
  primary:
    background: '#1B1B1B'
    foreground: '#93a1a1'
  normal:
    black:   '#263640'
    red:     '#d12f2c'
    green:   '#819400'
    yellow:  '#b08500'
    blue:    '#2587cc'
    magenta: '#696ebf'
    cyan:    '#289c93'
    white:   '#bfbaac'
  bright:
    black:   '#4a697d'
    red:     '#fa3935'
    green:   '#a4bd00'
    yellow:  '#d9a400'
    blue:    '#2ca2f5'
    magenta: '#8086e8'
    cyan:    '#33c5ba'
    white:   '#fdf6e3'
